name: tiny_pkce

repository: https://github.com/ElectricCookie/tiny_pkce

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
  test:selective_unit_test:
    run: melos exec --dir-exists="test" --fail-fast -- flutter test --no-pub --coverage
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test
  test:
    run: melos run test:selective_unit_test --no-select
    description: Run all  tests in this project.
  gen_coverage:
    run: melos exec -- "\$MELOS_ROOT_PATH/combine_coverage.sh"
    description: Generate coverage report for this project.
