name: tiny_pkce_launcher
description: "Used to trigger the iOS Auth Flow"
version: 0.0.2-dev.0
repository: https://github.com/ElectricCookie/tiny_pkce

environment:
  sdk: ^3.5.4
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TinyPkceLauncherPlugin
      macos:
        pluginClass: TinyPkceLauncherPlugin
