name: Dart

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          channel: "stable"

      - name: Install Melos
        run: flutter pub global activate melos

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "gh-actions@github.com"

      - name: Bootstrap dependencies with Melos
        run: melos bootstrap

      - name: Verify formatting (all packages)
        run: melos run format

      - name: Analyze (all packages)
        run: melos run analyze

      - name: Run tests (all packages)
        run: melos run test

      - name: Configure git (for versioning)
        run: |
          git fetch --prune --unshallow
      - name: 🔂 Run standard-version
        run: |
          npx standard-version --skip.tag --skip.commit ${{ github.base_ref == 'dev' && '--prerelease' || '' }}
      - name: ⏎ Get new version
        uses: actions/github-script@v7
        id: get_new_version
        with:
          result-encoding: string
          script: |
            const fs = require('fs');
            const package = JSON.parse(fs.readFileSync('package.json', 'utf8'));
            return package.version;
      - name: 💬 Comment on PR with new version
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "New version ${{ steps.get_new_version.outputs.result }} 🚀 "
